#ifndef _PEFF_CONTAINERS_BASEDEFS_H_
#define _PEFF_CONTAINERS_BASEDEFS_H_

#include <peff/base/basedefs.h>

#if PEFF_DYNAMIC_LINK
	#if IS_PEFF_CONTAINERS_BUILDING
		#define PEFF_CONTAINERS_API PEFF_DLLEXPORT
	#else
		#define PEFF_CONTAINERS_API PEFF_DLLIMPORT
	#endif
#else
	#define PEFF_CONTAINERS_API
#endif

#endif
