#ifndef _PEFF_CONTAINERS_BASEDEFS_H_
#define _PEFF_CONTAINERS_BASEDEFS_H_

#include <peff/base/basedefs.h>

#if IS_PEFF_CONTAINERS_BUILDING
	#define PEFF_CONTAINERS_API PEFF_DLLEXPORT
#else
	#define PEFF_CONTAINERS_API PEFF_DLLIMPORT
#endif

#endif
